version: "3.9"
services:
  web:
    build:
      context: .
      target: dev
    ports:
      - "8000:8000"
    command: python management_interface/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:15.2
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
